name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy -- -D warnings

  code-coverage-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        env:
          ETHPLORER_API_KEY: ${{ secrets.ETHPLORER_API_KEY }}
          MESSARIIO_KEY: ${{ secrets.MESSARIIO_KEY }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose -r